"""One-shot password reset tokens.

Token plaintext is generated by secrets.token_urlsafe(32). Only the
SHA-256 hash is stored in the DB so a DB read can't reveal active
tokens. TTL 1 hour.
"""
import hashlib
import secrets
import sqlite3
from datetime import datetime, timedelta, timezone
from typing import Optional


RESET_TTL_HOURS = 1


def _now() -> datetime:
    return datetime.now(timezone.utc)


def _hash(token: str) -> str:
    return hashlib.sha256(token.encode("utf-8")).hexdigest()


def create_reset_token(conn: sqlite3.Connection, user_id: int) -> str:
    token = secrets.token_urlsafe(32)
    now = _now()
    expires = now + timedelta(hours=RESET_TTL_HOURS)
    conn.execute(
        "INSERT INTO password_resets(token_hash,user_id,created_at,"
        "expires_at) VALUES(?,?,?,?)",
        (_hash(token), user_id, now.isoformat(), expires.isoformat()),
    )
    conn.commit()
    return token


def consume_reset_token(
    conn: sqlite3.Connection, token: str
) -> Optional[int]:
    row = conn.execute(
        "SELECT user_id, expires_at, consumed_at FROM password_resets "
        "WHERE token_hash=?", (_hash(token),)
    ).fetchone()
    if not row:
        return None
    user_id, expires_at, consumed_at = row
    if consumed_at is not None:
        return None
    if datetime.fromisoformat(expires_at) <= _now():
        return None
    conn.execute(
        "UPDATE password_resets SET consumed_at=? WHERE token_hash=?",
        (_now().isoformat(), _hash(token)),
    )
    conn.commit()
    return user_id
